version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.15.3-stretch
    steps:
      - checkout
      - RUN: npm ci
      - RUN: npm audit --audit-level=moderate
      - RUN: npm run flow
      - RUN: npm run prettier
      - RUN: npm run build
