backend:
  name: github
  repo: writespeakcode/writespeakcode.com
  branch: production

media_folder: static/images
public_folder: /images

site_url: https://writespeakcode.netlify.com
logo_url: https://raw.githubusercontent.com/WriteSpeakCode/writespeakcode.com/production/src/images/logos/wsc-logo-fullcolor.png

publish_mode: editorial_workflow
show_preview_links: false

collections:
  - name: 'pages'
    label: 'Pages'
    description: 'Edit the copy of standalone pages on our site.'
    delete: false
    files:
      - file: 'content/code-of-conduct.md'
        label: 'Code of Conduct'
        name: 'code-of-conduct'
        fields:
          - label: 'Template Key'
            name: 'templateKey'
            widget: 'hidden'
            default: 'subpage'
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'

  - name: 'speakers'
    label: 'Speakers'
    identifier_field: name
    label_singular: 'Speaker'
    description: 'Add, edit, or delete speakers here. Speakers here are used on conference pages and the speaker directory.'
    delete: true
    create: true
    folder: 'content/speakers'
    extension: 'json'
    fields:
      - label: 'Name'
        name: 'name'
        widget: 'string'
      - label: 'Pronouns'
        name: 'pronouns'
        widget: 'string'
        required: false
      - label: 'Role/Company'
        name: 'role'
        widget: 'string'
        required: false
      - label: 'Social Links'
        name: 'links'
        widget: 'list'
        required: false
        fields:
          - label: 'Type'
            name: 'type'
            widget: 'select'
            options: ['twitter', 'linkedin', 'github', 'website', 'other']
          - label: 'URL'
            name: 'url'
            widget: 'string'
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'speaker'
      - label: 'Headshot'
        name: 'headshot'
        widget: 'image'
        required: false
      - label: 'Bio'
        name: 'bio'
        widget: 'text'
        required: false

  - name: 'sponsorship_packages'
    label: 'Sponsorship Packages'
    label_singular: 'Sponsorship Package'
    identifier_field: name
    folder: 'content/sponsorship_packages'
    editor:
      preview: false
    fields:
      - label: 'Name'
        name: 'name'
        widget: 'string'
        required: true
      - label: 'Type'
        name: 'type'
        widget: 'select'
        options: ['conference', 'event']
        required: true

  - name: 'sponsors'
    label: 'Sponsors'
    identifier_field: company
    label_singular: 'Sponsor'
    description: 'Add, edit, or delete sponsors here. Sponsors are shown on the organization page and the conference pages.'
    delete: true
    create: true
    folder: 'content/sponsors'
    extension: 'json'
    editor:
      preview: false
    fields:
      - label: 'Company'
        name: 'company'
        widget: 'string'
        required: true
      - label: 'Company URL'
        name: 'company_url'
        widget: 'string'
        required: false
      - label: 'Logo'
        name: 'logo'
        widget: 'image'
        required: false
      - label: 'Company Text'
        name: 'company_text'
        widget: 'text'
        required: false
      - label: 'Sponsorships'
        name: 'sponsorships'
        widget: 'list'
        fields:
          - { label: Year, name: year, widget: string, default: '2019' }
          - label: 'Package(s)'
            name: 'packages'
            widget: 'relation'
            collection: 'sponsorship_packages'
            searchFields: ['name']
            valueField: 'name'
            displayFields: ['name', 'type']
            multiple: true

  - name: 'testimonials'
    label: 'Testimonials'
    identifier_field: quote
    label_singular: 'Testimonial'
    description: 'Add, edit, or delete testimonials here. Testimonials will be shown across the website.'
    delete: true
    create: true
    folder: 'content/testimonials'
    extension: 'json'
    fields:
      - label: 'Quote'
        name: 'quote'
        widget: 'text'
        required: true
      - label: 'Name'
        name: 'name'
        widget: 'string'
        required: true
      - label: 'URL Source'
        name: 'url_source'
        widget: 'string'
        required: false
